#!/usr/bin/env bash

echo "--create bucket--"

# Check if the first argument (bucket name) is provided
if [ -z "$1" ]; then
    echo "There needs to be a bucket name, e.g., ./bucket my-bucket"
    exit 1
fi

BUCKET_NAME = $1; 

# Create the S3 bucket using the provided name

aws s3api create-bucket --bucket $BUCKET_NAME \
 --create-bucket-configuration="LocationConstraint=ca-central-1" \
 --output="text"

